#!/usr/bin/env bash
set -euo pipefail

# This is a black-box test: it starts a temporary smtp2web process and talks
# to it only through SMTP and HTTP. It never reads or changes the configured
# production service, its queue, certificates, logs, or systemd state.
APP_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd -P)
TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/smtp2web-integration.XXXXXX")
GATEWAY_PID=''
SERVER_PID=''

log() {
  printf '[integration] %s\n' "$*"
}

cleanup() {
  # Always stop child processes first. Keeping the temporary directory is
  # useful when diagnosing a failure, but leaving listeners behind is not.
  if [ -n "$SERVER_PID" ]; then kill "$SERVER_PID" 2>/dev/null || true; fi
  if [ -n "$GATEWAY_PID" ]; then kill "$GATEWAY_PID" 2>/dev/null || true; fi
  wait "$SERVER_PID" 2>/dev/null || true
  wait "$GATEWAY_PID" 2>/dev/null || true
  if [ "${SMTP2WEB_TEST_KEEP:-0}" = '1' ]; then
    log "temporary test files kept at $TEST_ROOT"
  else
    rm -rf "$TEST_ROOT"
  fi
}
trap cleanup EXIT

for command in node python3 swaks curl openssl; do
  command -v "$command" >/dev/null || {
    echo "missing integration-test prerequisite: $command" >&2
    exit 1
  }
done

free_port() {
  # The listener is started immediately afterwards. A short-lived probe avoids
  # fixed ports while keeping the suite suitable for concurrent local use.
  python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'
}

wait_for_file() {
  local file=$1
  for _ in $(seq 1 100); do
    [ -s "$file" ] && return 0
    sleep 0.05
  done
  echo "timed out waiting for $file" >&2
  return 1
}

wait_for_smtp() {
  for _ in $(seq 1 100); do
    if python3 -c 'import socket, sys; s = socket.create_connection(("127.0.0.1", int(sys.argv[1])), 0.1); s.close()' "$SMTP_PORT" 2>/dev/null; then
      return 0
    fi
    sleep 0.05
  done
  echo "timed out waiting for SMTP listener on $SMTP_PORT" >&2
  return 1
}

request_count() {
  # The fake gateway exposes received requests only to this loopback runner.
  curl --silent --show-error --fail "http://127.0.0.1:${GATEWAY_PORT}/__received" \
    | python3 -c 'import json, sys; print(len(json.load(sys.stdin)["requests"]))'
}

wait_for_count() {
  local expected=$1
  for _ in $(seq 1 200); do
    [ "$(request_count)" -ge "$expected" ] && return 0
    sleep 0.05
  done
  echo "timed out waiting for $expected gateway requests" >&2
  return 1
}

configure_gateway() {
  local actions=$1
  # Responses are consumed in order, allowing a scenario such as 500 then 200
  # without changing smtp2web's forwarding configuration.
  curl --silent --show-error --fail \
    --request POST \
    --header 'Content-Type: application/json' \
    --data "{\"actions\":${actions}}" \
    "http://127.0.0.1:${GATEWAY_PORT}/__control" >/dev/null
}

assert_last_request() {
  local subject=$1
  local idempotency=$2
  curl --silent --show-error --fail "http://127.0.0.1:${GATEWAY_PORT}/__received" \
    | python3 -c '
import json
import sys
subject, idempotency = sys.argv[1:]
request = json.load(sys.stdin)["requests"][-1]
payload = json.loads(request["body"])
# Assert at the actual HTTP boundary, rather than relying solely on application
# logs, that smtp2web preserved the parsed subject and header behavior.
assert payload["mail"]["subject"] == subject, payload
header = request["headers"].get("Idempotency-Key")
if idempotency == "absent":
    assert header is None, request["headers"]
else:
    assert header == payload["meta"]["messageId"], (header, payload)
' "$subject" "$idempotency"
}

send_mail() {
  local subject=$1
  swaks \
    --server 127.0.0.1 \
    --port "$SMTP_PORT" \
    --tls \
    --from sender@example.test \
    --to receiver@example.test \
    --header "Subject: $subject" \
    --body "smtp2web integration test: $subject" \
    >/dev/null
}

start_instance() {
  local idempotency_enabled=$1
  SMTP_PORT=$(free_port)
  SPOOL="$TEST_ROOT/spool"
  LOG="$TEST_ROOT/smtp2web.log"
  CONFIG="$TEST_ROOT/config.json"

  # Generate a complete, isolated configuration. Fast retry and timeout values
  # keep failure scenarios quick without affecting production settings.
  TEST_ROOT="$TEST_ROOT" SMTP_PORT="$SMTP_PORT" GATEWAY_PORT="$GATEWAY_PORT" \
    IDEMPOTENCY_ENABLED="$idempotency_enabled" python3 - <<'PY'
import json
import os

root = os.environ['TEST_ROOT']
# All paths intentionally point below the temporary root. The self-signed
# certificate is generated by smtp2web during startup.
config = {
  'smtp': {
    'name': 'localhost', 'listen': '127.0.0.1',
    'port': int(os.environ['SMTP_PORT']), 'requireTLS': True,
    'maxMessageBytes': 1024 * 1024,
    'tls': {
      'minVersion': 'TLSv1.2', 'maxVersion': 'TLSv1.3',
      'selfSignedDays': 1, 'subjectAltNames': ['localhost'],
      'ciphers': ['TLS_AES_256_GCM_SHA384', 'TLS_AES_128_GCM_SHA256'],
      'key': os.path.join(root, 'certs', 'private.pem'),
      'cert': os.path.join(root, 'certs', 'public.pem'),
    },
  },
  'queue': {
    'path': os.path.join(root, 'spool'), 'retryIntervalSeconds': 1,
    'validateIntervalSeconds': 1, 'maxAttempts': 3,
    'failedPath': os.path.join(root, 'spool', 'failed'),
  },
  'forwarder': {
    'endpoint': 'http://127.0.0.1:%s/mail' % os.environ['GATEWAY_PORT'],
    'format': 'json', 'timeoutSeconds': 1,
    'idempotency': {'enabled': os.environ['IDEMPOTENCY_ENABLED'] == 'true', 'header': 'Idempotency-Key'},
  },
  'archive': {'enabled': False, 'path': os.path.join(root, 'archive')},
  'log': {'path': os.path.join(root, 'smtp2web.log')},
}
with open(os.path.join(root, 'config.json'), 'w', encoding='utf-8') as output:
    json.dump(config, output)
PY

  SMTP2WEB_CONFIG="$CONFIG" node "$APP_DIR/server.js" >"$TEST_ROOT/server.stderr" 2>&1 &
  SERVER_PID=$!
  if ! wait_for_file "$LOG"; then
    cat "$TEST_ROOT/server.stderr" >&2 || true
    return 1
  fi
  grep -q 'smtp server started' "$LOG"
  if ! wait_for_smtp; then
    cat "$TEST_ROOT/server.stderr" >&2 || true
    return 1
  fi
  log "smtp2web started on 127.0.0.1:${SMTP_PORT} (idempotency: ${idempotency_enabled})"
}

stop_instance() {
  # Test 6 restarts with a fresh config so the opt-in header is checked without
  # changing the default receiver-compatible behavior tested above.
  kill "$SERVER_PID" 2>/dev/null || true
  wait "$SERVER_PID" 2>/dev/null || true
  SERVER_PID=''
}

# Binding port 0 asks the operating system for a free loopback HTTP port.
python3 "$APP_DIR/test/integration/fake_gateway.py" \
  --ready-file "$TEST_ROOT/gateway-ready.json" >"$TEST_ROOT/gateway.stderr" 2>&1 &
GATEWAY_PID=$!
wait_for_file "$TEST_ROOT/gateway-ready.json"
GATEWAY_PORT=$(python3 -c 'import json, sys; print(json.load(open(sys.argv[1]))["port"])' "$TEST_ROOT/gateway-ready.json")
log "fake API gateway started on 127.0.0.1:${GATEWAY_PORT}"

start_instance false

log 'test 1/6: STARTTLS mail with HTTP 200 is forwarded once'
configure_gateway '[200]'
send_mail 'accepted over STARTTLS'
wait_for_count 1
assert_last_request 'accepted over STARTTLS' absent

log 'test 2/6: plaintext SMTP is rejected when TLS is required'
if swaks --server 127.0.0.1 --port "$SMTP_PORT" --from sender@example.test --to receiver@example.test --body plaintext >/dev/null 2>&1; then
  echo 'plaintext SMTP was accepted although TLS is required' >&2
  exit 1
fi

log 'test 3/6: HTTP 202 is accepted as successful asynchronous delivery'
configure_gateway '[202]'
send_mail 'accepted asynchronously'
wait_for_count 2
assert_last_request 'accepted asynchronously' absent

log 'test 4/6: HTTP 500 keeps the item queued and retries successfully'
configure_gateway '[500, 200]'
send_mail 'retry after gateway failure'
wait_for_count 4
assert_last_request 'retry after gateway failure' absent

log 'test 5/6: corrupt spool JSON is moved directly to quarantine'
printf '{not json\n' >"$SPOOL/corrupt.json"
for _ in $(seq 1 100); do
  [ -e "$SPOOL/quarantine/corrupt.json" ] && break
  sleep 0.05
done
[ -e "$SPOOL/quarantine/corrupt.json" ]

stop_instance
start_instance true
log 'test 6/6: idempotency opt-in sends the stable message identifier header'
configure_gateway '[200]'
send_mail 'idempotency opt-in'
wait_for_count 5
assert_last_request 'idempotency opt-in' present

log 'all smtp2web integration tests passed'
